import { supabase } from "./supabase";
import { DEFAULT_SQUARE_SET, displaySquareSet } from "./squareSets";
import { overlayConfigFile } from "./overlayConfig";

/**
 * The player's side of auto-marking: the token the game mod carries, and who may have one.
 *
 * -- What auto-marking is -------------------------------------------------------------------------
 *
 * A mod running inside Elden Ring notices when a boss dies and reports it to the `auto-fire` edge
 * function, which works out which square that boss occupies on the player's current board and fires
 * the shot. Under fire-on-kill the click timestamp IS the kill time, so doing it by hand bakes a
 * couple of seconds of alt-tabbing into every record; this removes that.
 *
 * Nothing here talks to the mod. The website's whole contribution is minting the token a player
 * pastes into it once, and saying whether the current board supports the feature at all.
 */

/**
 * Auto-marking only works on the boss board.
 *
 * The objectives sets are counters and judgement calls - "collect 4 unique helms", "kill 3 bosses
 * that do not wield weapons" - and no event flag can settle any of them. This is a permanent
 * property of those sets rather than a gap someone will fill in later, which is why the UI hides
 * auto-marking entirely on them rather than showing it disabled: a control that can never become
 * available is just noise on the screen.
 *
 * `null` means the room predates square sets and is therefore on the default, which is the boss set.
 *
 * Asked of the DISPLAYED set, so both cuts of the boss board answer yes: the small-crew cut is the
 * same squares with the far end taken out, and every one of them has an event flag.
 */
export function autoFireSupported(squareSetId: string | null | undefined): boolean {
  return displaySquareSet(squareSetId) === DEFAULT_SQUARE_SET;
}

/**
 * Reads the signed-in player's token, or null if they've never made one.
 *
 * Row-level security scopes this to the caller's own row, so there is no player id to pass and no
 * way to read anyone else's. An anonymous session simply matches nothing.
 */
export async function fetchIngestToken(): Promise<string | null> {
  const { data, error } = await supabase.from("ingest_tokens").select("token").maybeSingle();
  if (error) throw error;
  return data?.token ?? null;
}

/**
 * Mints a token for the signed-in player.
 *
 * The string itself is generated by the database (`gen_random_bytes`), not here. Keeping it server
 * side means one definition of the format and no dependence on how good the browser's randomness
 * happens to be.
 */
export async function createIngestToken(): Promise<string> {
  const { data: session } = await supabase.auth.getUser();
  const userId = session.user?.id;
  if (!userId) throw new Error("Not signed in");

  const { data, error } = await supabase
    .from("ingest_tokens")
    .insert({ user_id: userId })
    .select("token")
    .single();
  if (error) throw error;
  return data.token as string;
}

/**
 * Replaces the token, invalidating the old one immediately.
 *
 * Delete then insert rather than an update, so the new string comes from the same database default
 * as the original - an update would mean generating it in the browser instead. The unique constraint
 * on user_id is what makes this safe: there is only ever one row to replace, so there is no way to
 * end up with a set of old tokens still quietly working.
 */
export async function regenerateIngestToken(): Promise<string> {
  const { data: session } = await supabase.auth.getUser();
  const userId = session.user?.id;
  if (!userId) throw new Error("Not signed in");

  const { error: delError } = await supabase.from("ingest_tokens").delete().eq("user_id", userId);
  if (delError) throw delError;
  return createIngestToken();
}

/** Where the mod sends its kill reports. Same project as everything else the site talks to. */
export function ingestUrl(): string {
  return `${import.meta.env.VITE_SUPABASE_URL as string}/functions/v1/auto-fire`;
}

/**
 * The whole config file a player pastes into the mod, with their token in it.
 *
 * Handed over as an entire file rather than as the three lines that matter, because "find the
 * [ingest] section and replace exactly that, without leaving the old one behind" is several
 * instructions and every one of them ends in a config TOML will not parse. Select all, paste, save
 * cannot be got half right.
 *
 * The template lives in ./overlayConfig, which knows nothing about this app; the endpoint URL is
 * passed into it so there is still one definition of where kills go.
 */
export function configFile(token: string): string {
  return overlayConfigFile(token, ingestUrl());
}

/** Enough of the token to recognise it, without putting the whole secret on screen. */
export function maskToken(token: string): string {
  return token.length <= 12 ? token : `${token.slice(0, 6)}${"·".repeat(8)}${token.slice(-4)}`;
}
