-- One permanent token per player, so an OBS scene can be installed once and never touched again.
--
-- -- The problem this solves ----------------------------------------------------------------------
--
-- Every overlay URL the site hands out today names a room: /overlay-board/AB12CD. That is correct
-- for what those sources are, and it is also why a streamer edits seven Browser Sources before every
-- single match. The scene they spent an evening arranging - moved, resized, filtered, ordered - is
-- fine; the seven URLs inside it are stale the moment the room changes.
--
-- So this is the same trick ingest_tokens plays for auto-marking, aimed at overlays: the token names
-- the PLAYER, and the room is resolved at read time from the seat they are already sitting in. The
-- Browser Source URLs never change, and the scene follows them from match to match.
--
--     Match 101  ->  same token  ->  Match 102  ->  same token  ->  Match 103
--
-- -- Why NOT the auto-fire token ------------------------------------------------------------------
--
-- An ingest token can fire shots. It is a write credential, and an OBS Browser Source URL is about
-- the least private string a streamer owns: it sits in a config file, in scene-collection exports
-- they trade with each other, in screen shares, and in the URL bar of any browser dock they happen
-- to open. Putting a write credential there would mean anybody who ever saw the streamer's OBS could
-- fire their shots for them, for the rest of the season.
--
-- Nor the rejoin code, for the same reason and worse: claim_player_slot() will hand its holder the
-- seat outright.
--
-- Hence a third credential that can do exactly one thing.
--
-- -- Blast radius of a leaked overlay token -------------------------------------------------------
--
-- Someone can watch the overlay of a player whose stream they could already have watched. That is
-- the whole of it. It reaches two read-only functions, neither of which writes anything, and between
-- them they return a room code, a team number, and that player's own ship layout - which is the one
-- genuinely sensitive thing here, and is why the fleet lives behind its own call rather than being
-- bundled into the session (see below).
--
-- It grants no writes anywhere, is not accepted by auto-fire or by any gameplay path, cannot be
-- redeemed for a seat, and reads nothing about the account behind it - no email, no Twitch id, no
-- profile row. Rotating it is a delete and an insert, and the old string stops working immediately.

create table if not exists public.overlay_tokens (
  -- 32 hex characters, generated by the database rather than by a browser, so there is one
  -- definition of the format and no dependence on how good a given browser's randomness happens to
  -- be. No dashes and no casing, because this ends up pasted into URLs by hand.
  --
  -- -- Why not encode(gen_random_bytes(24), 'hex'), the way ingest_tokens does -------------------
  --
  -- Because it does not apply. gen_random_bytes comes from pgcrypto, which on Supabase is installed
  -- into the `extensions` schema, and the role that runs migrations does not carry that schema on
  -- its search path - so this table failed to create with `function gen_random_bytes(integer) does
  -- not exist`. A column default is parsed and resolved when the column is CREATED, not when a row
  -- is inserted, so it is no help that the same call resolves fine for PostgREST at runtime. That is
  -- why ingest_tokens, written when the search path was arranged differently, is still standing
  -- while an identical default refused to be created today.
  --
  -- Schema-qualifying it to extensions.gen_random_bytes would work on this project and quietly break
  -- on any project that has pgcrypto somewhere else, including a fresh `supabase db reset`. So the
  -- dependency goes instead: gen_random_uuid() is core Postgres, needs no extension and no schema
  -- qualification, and every primary key in this schema already proves it resolves here.
  --
  -- Strength is not the trade it looks like. A v4 UUID is 122 bits from the same CSPRNG pgcrypto
  -- draws on, which is far past guessable for a credential whose worst case is letting somebody
  -- watch an overlay. Stripping the dashes keeps it one word in a URL.
  token       text primary key default replace(gen_random_uuid()::text, '-', ''),
  user_id     uuid not null default auth.uid() references auth.users(id) on delete cascade,
  created_at  timestamptz not null default now(),

  -- One live token per person. Rotation replaces this row rather than adding a second, so there is
  -- never a set of old tokens quietly still working in a scene somebody forgot about.
  unique (user_id)
);

alter table public.overlay_tokens enable row level security;

-- No public select policy. Like ingest_tokens and unlike everything else here, this table holds a
-- secret: even its owner reads only their own row, and nobody can enumerate it. The overlay itself
-- never selects from this table at all - it calls the security-definer functions below, which is
-- what lets an anonymous browser source resolve a token it is not allowed to read.
drop policy if exists "overlay_tokens select own" on public.overlay_tokens;
create policy "overlay_tokens select own" on public.overlay_tokens
  for select using (user_id = auth.uid());

drop policy if exists "overlay_tokens insert own" on public.overlay_tokens;
create policy "overlay_tokens insert own" on public.overlay_tokens
  for insert with check (user_id = auth.uid());

-- `with check` as well as `using`, so a row cannot be updated into somebody else's name.
drop policy if exists "overlay_tokens update own" on public.overlay_tokens;
create policy "overlay_tokens update own" on public.overlay_tokens
  for update using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "overlay_tokens delete own" on public.overlay_tokens;
create policy "overlay_tokens delete own" on public.overlay_tokens
  for delete using (user_id = auth.uid());

comment on table public.overlay_tokens is
  'Per-user permanent READ-ONLY credential for stream overlays. Resolved by overlay_session() and overlay_token_fleet(); never accepted by auto-fire, claim_player_slot, or any gameplay write.';


-- --- overlay_session -----------------------------------------------------------------------------
--
-- token -> which match is this person in right now.
--
-- The token deliberately encodes nothing. Everything match-specific is resolved here, on every call,
-- which is exactly what makes one token survive a season: switching fleets, joining another room,
-- leaving one, and playing five matches back to back all work with no reconfiguration, because none
-- of it is in the token to go stale.
--
-- SECURITY DEFINER because the caller is an OBS Browser Source - a fresh anonymous session that owns
-- nothing and is a member of no room. It cannot read overlay_tokens (there is no policy that would
-- let it), and proving which player it belongs to is the entire point of the call.
--
-- -- What it deliberately does NOT return ---------------------------------------------------------
--
-- No rejoin code, no ingest token, no email, no profile row, no fleet. The overlay pages take a room
-- code and a team and render from the public log, exactly as they do today when a streamer pastes a
-- room URL in by hand - so this returns precisely the two values that URL carried, plus the user id
-- the client needs to watch for its own seat changing (see the realtime note in useOverlayToken).
-- That id is already world-readable off `players`, which every spectator selects freely.
--
-- Named columns rather than a row type for the same reason the rest of this schema does it: the
-- Supabase egress work wants explicit projections, and `select *` on a joined room row would ship a
-- board permutation and a ship_defs blob to a browser source that has no use for either.
--
-- -- Why a valid token ALWAYS gets a row ----------------------------------------------------------
--
-- The seat is left-joined, so a token whose owner is in no room at all still answers - with a null
-- room and that one user id. That is not a convenience; it is what lets the overlay be event-driven
-- instead of polling. The client watches `players` filtered to that id and re-resolves when a seat
-- appears, changes or vanishes, and without the id from this call there would be nothing to filter
-- on and no choice but to ask the database every few seconds for the rest of the stream's life.
--
-- An INVALID token still gets nothing, which is the distinction that matters: the empty set means
-- "there is no such token", and a row with a null room means "real token, nobody playing".
create or replace function public.overlay_session(p_token text)
returns table (
  room_code   text,
  room_status text,
  team        int,
  user_id     uuid
)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Empty set rather than an exception, throughout. A missing, rotated or mistyped token means "this
  -- player is not in a match", which is the same thing the overlay draws when they genuinely are not:
  -- nothing. A browser source that raises is a black rectangle on somebody's stream.
  if p_token is null or length(trim(p_token)) = 0 then
    return;
  end if;

  return query
  select r.code, r.status, seat.team, t.user_id
    from overlay_tokens t
    -- One seat, when there is more than one to choose from. Unlike auto-fire - which refuses an
    -- ambiguous match outright, because a shot cannot be taken back - an overlay only draws, so
    -- guessing wrong costs a few seconds of the wrong board and fixes itself. The order is what a
    -- streamer would pick: the match actually being played, then the one about to be, then the
    -- lobby they are sitting in, then the one that just ended; most recently joined breaks the tie.
    --
    -- Lateral rather than a plain join because the ordering that picks the seat has to see the
    -- room's status, and the outer join has to stay LEFT so a player with no seat still answers.
    left join lateral (
      select p.team, p.room_id
        from players p
        join rooms  pr on pr.id = p.room_id
       where p.user_id = t.user_id
       order by case pr.status
                  when 'battle'    then 0
                  when 'placement' then 1
                  when 'lobby'     then 2
                  else 3
                end,
                p.joined_at desc
       limit 1
    ) seat on true
    left join rooms r on r.id = seat.room_id
   where t.token = trim(p_token);
end;
$$;

-- anon as well as authenticated: an OBS Browser Source is a fresh context with no saved session, and
-- may not have signed in even anonymously by the time it asks.
grant execute on function public.overlay_session(text) to anon, authenticated;


-- --- overlay_token_fleet -------------------------------------------------------------------------
--
-- token -> the ships of the player who owns it, in whatever room they are currently in.
--
-- public.overlay_fleet() already does this for a room code plus a rejoin code, and this is that
-- function with a safer credential and the room resolved rather than passed. Worth having as its own
-- call rather than as columns on overlay_session for one reason: this is the only genuinely
-- sensitive thing either function returns, and the four sources that draw nothing but public data
-- should not be shipped a ship layout on the way past.
--
-- Same absolute rule as overlay_fleet, and it matters more here: READ ONLY, forever. This must never
-- grow into anything that calls claim_player_slot() to identify itself - that re-points the player
-- row at the caller, and a streamer's own overlay would silently steal their seat mid-match.
create or replace function public.overlay_token_fleet(p_token text)
returns table (
  team                int,
  placements          jsonb,
  ship_sunk           jsonb,
  ship_hits_remaining jsonb,
  placement_confirmed boolean
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_token is null or length(trim(p_token)) = 0 then
    return;
  end if;

  return query
  select f.team, f.placements, f.ship_sunk, f.ship_hits_remaining, f.placement_confirmed
    from overlay_tokens t
    join players p on p.user_id = t.user_id
    join rooms   r on r.id = p.room_id
    join fleets  f on f.room_id = p.room_id and f.team = p.team
   where t.token = trim(p_token)
     and p.team is not null
   -- The same seat overlay_session picked, by the same ordering - otherwise a player seated in two
   -- rooms could get one room's board with the other room's ships drawn on it.
   order by case r.status
              when 'battle'    then 0
              when 'placement' then 1
              when 'lobby'     then 2
              else 3
            end,
            p.joined_at desc
   limit 1;
end;
$$;

grant execute on function public.overlay_token_fleet(text) to anon, authenticated;
